feriaVirtual/core/urls.py
from django.contrib.auth.views import login_required
from django.urls import path, include
from .views import *
from . import views

#esta url en core se encarga de rutear las views

urlpatterns = [
   path('', home, name="home"),
   path('login', login, name="login"),
   path('logout/', logout, name="logout"),
   path('registro', registro, name="registro"),
   path('detalle/', detalle, name="detalle"),
   path('comprar/', login_required(comprar), name="comprar"),
   path('transbank',login_required(transbank), name='transbank'),
   path('medioPago', login_required(medioPago), name="medioPago"),
   path('usuario/', login_required(usuario), name="usuario"),

   path('usuario_2/', login_required(usuario_2), name="usuario_2"),


   path('usuario/pedido', login_required(pedido), name="pedido"),
   path('usuario/informacion', login_required(informacion), name="informacion"),
   path('administracion/', login_required(homeAdmin), name="homeAdmin"),
   path('administracion/solicitud', login_required(solicitudAdmin), name="solicitudAdmin"),
   path('administracion/solicitud_detalle', login_required(detallesolicitudAdmin), name="detallesolicitudAdmin"),
   path('administracion/publicar_venta_local', login_required(publicar_venta_local), name="ventalocal_publicar"),
   path('administracion/detalle_saldos', login_required(detalle_publicar_vl), name="ventalocal_publicar_detalle"),
   path('administracion/publicacion_vl', login_required(publicacion_vl), name="publicacion_vl"),
   
   path('portalDeOfertas', login_required(portalDeOfertas), name="portalDeOfertas"),

   path('detallePedido', login_required(detallePedido), name="detallePedido"),
   path('usuario/historial_compra',login_required(historial_compra), name= "historial_compra"),
   path('usuario/detalle_historial_compra',login_required(detalle_historial_compra), name= "detalle_historial_compra"),
   path('usuario/historial_ofertas', login_required(historial_ofertas), name="historial_ofertas"),
   path('usuario/detalle_hitorial_ofertas', login_required(datalle_historial_ofertas), name="detalle_historial_ofertas"),
   path('oferta_productor', login_required(ofertaProductor), name="oferta_productor"),
   path('informacion_empresa', info_empresa, name="info_empresa"),

   path('usuario/ordenes', login_required(ordenes_externo), name="ordenesExterno"),
   path('usuario/ordenes_detalle', login_required(ordenes_externo_detalle), name="ordenExterno_detalle"),
   path('usuario/puntos', dashboard_puntos, name="puntos"),


   path('usuario/solicitud', login_required(solicitud), name="solicitud"),
   path('ajax/crud/create/', CreateCrudUser.as_view(), name='crud_ajax_create'),
   path('ajax/crud/create_2/', CreateCrudUser2.as_view(), name='crud_ajax_create2'),
   #-------------PDF
   path('pdf_view/', views.ViewPDF.as_view(), name="pdf_view"),
   path('pdf_download/', views.DownloadPDF.as_view(), name="pdf_download"),

   path('variedad/', variedad_por_especie, name="variedad"),

   path('administracion/publicaciones_ofertadas', login_required(revisar_publicaciones_pedidos), name="revisar_publicaciones_pedidos"),
   path('administracion/detalle_publicacion_ofertada', login_required(revisar_detalle_pedido), name="revisar_detalle_pedido"),
   path('usuario/ventas_cerradas', ventas_cerradas, name="ventas_cerradas"),
   path('usuario/contacto', contactanos, name = "contactanos"),



#-------------------------------------------------------------------------------
   
   path('p_oferta', p_oferta, name='p_oferta'),
   path('grafico/', ver, name="grafico"),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

feriaVirtual/feriaVirtual/urls.py
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.urls import path,include,re_path
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')), 
]


urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

feriaVirtual/core/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

#---------------------------------
class pruebadetalle(models.Model):
    especie = models.CharField(max_length=30)
    variedad = models.CharField(max_length=30)
    cantidad = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'pruebadetalle'
    
#---------------------------------

class Calidad(models.Model):
    id_calidad = models.IntegerField(primary_key=True)
    detalle = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'calidad'


class Calificacion(models.Model):
    id_calificacion = models.IntegerField(primary_key=True)
    des_calificacion = models.CharField(max_length=50)
    id_usuario = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usuario', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'calificacion'


class Comuna(models.Model):
    id_comuna = models.IntegerField(primary_key=True)
    des_comuna = models.CharField(max_length=50)
    id_provincia = models.ForeignKey('Provincia', models.DO_NOTHING, db_column='id_provincia')

    class Meta:
        managed = False
        db_table = 'comuna'


class Contrato(models.Model):
    id_contrato = models.IntegerField(primary_key=True)
    fecha_inicio = models.DateField()
    fecha_termino = models.DateField()
    vigencia = models.CharField(max_length=1)
    id_usuario = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usuario', blank=True, null=True)
    id_estado = models.ForeignKey('EstadoContrato', models.DO_NOTHING, db_column='id_estado')

    class Meta:
        managed = False
        db_table = 'contrato'


class Costos(models.Model):
    id_costo = models.IntegerField(primary_key=True)
    descripcion = models.CharField(max_length=30)
    valor = models.IntegerField(blank=True, null=True)
    id_orden = models.ForeignKey('OrdenCompra', models.DO_NOTHING, db_column='id_orden', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'costos'


class DetalleLocal(models.Model):
    id_detalle_local = models.IntegerField(primary_key=True)
    precio = models.IntegerField()
    kilo = models.IntegerField()
    descripcion = models.CharField(max_length=200, blank=True, null=True)
    id_calidad = models.ForeignKey(Calidad, models.DO_NOTHING, db_column='id_calidad')
    id_venta_local = models.ForeignKey('VentaLocal', models.DO_NOTHING, db_column='id_venta_local')
    id_stock = models.ForeignKey('StockSobrante', models.DO_NOTHING, db_column='id_stock')

    class Meta:
        managed = False
        db_table = 'detalle_local'


class DetalleOferta(models.Model):
    id_detalle_of = models.IntegerField(primary_key=True)
    kilo = models.IntegerField()
    precio = models.IntegerField()
    fecha_cosecha = models.DateField()
    id_oferta = models.ForeignKey('OfertaProductor', models.DO_NOTHING, db_column='id_oferta')
    id_publicacion = models.IntegerField()
    id_especie = models.ForeignKey('Especie', models.DO_NOTHING, db_column='id_especie')
    id_solicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='id_solicitud')

    class Meta:
        managed = False
        db_table = 'detalle_oferta'


class DetalleSolicitud(models.Model):
    id_pedido = models.IntegerField(primary_key=True)
    id_solicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='id_solicitud')
    id_especie = models.ForeignKey('Especie', models.DO_NOTHING, db_column='id_especie')
    kilos = models.DecimalField(max_digits=14, decimal_places=4)

    class Meta:
        managed = False
        db_table = 'detalle_solicitud'


class Empresa(models.Model):
    id_empresa = models.IntegerField(primary_key=True)
    rut_empresa = models.CharField(max_length=9)
    razon_social = models.CharField(max_length=50)
    giro_empresa = models.CharField(max_length=150)
    direccion_empresa = models.CharField(max_length=150)
    id_estado = models.ForeignKey('EstadoEmpresa', models.DO_NOTHING, db_column='id_estado')

    class Meta:
        managed = False
        db_table = 'empresa'


class Especie(models.Model):
    id_especie = models.IntegerField(primary_key=True)
    des_especie = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'especie'


class EstadoContrato(models.Model):
    id_estado = models.IntegerField(primary_key=True)
    des_estado = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'estado_contrato'


class EstadoEmpresa(models.Model):
    id_estado = models.IntegerField(primary_key=True)
    des_estado = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'estado_empresa'


class EstadoPedido(models.Model):
    id_estado = models.IntegerField(primary_key=True)
    desc_estado = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'estado_pedido'


class EstadoSolicitud(models.Model):
    id_estado = models.IntegerField(primary_key=True)
    des_estado = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'estado_solicitud'


class EstadoUsuario(models.Model):
    id_estado = models.IntegerField(primary_key=True)
    des_estado = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'estado_usuario'


class EstadoVenta(models.Model):
    id_estado = models.IntegerField(primary_key=True)
    des_estado = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'estado_venta'


class Imagen(models.Model):
    id_imagen = models.IntegerField(primary_key=True)
    desc_imagen = models.CharField(max_length=100)
    ext_imagen = models.CharField(max_length=6)
    imagen = models.BinaryField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'imagen'


class OfertaProductor(models.Model):
    id_oferta = models.IntegerField(primary_key=True)
    id_usuario = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usuario')
    id_orden = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'oferta_productor'


class OrdenCompra(models.Model):
    id_orden = models.IntegerField(primary_key=True)
    id_estado = models.ForeignKey(EstadoPedido, models.DO_NOTHING, db_column='id_estado', blank=True, null=True)
    total = models.IntegerField()
    id_solicitud = models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='id_solicitud')

    class Meta:
        managed = False
        db_table = 'orden_compra'


class Pago(models.Model):
    id_pago = models.IntegerField(primary_key=True)
    descripcion = models.CharField(max_length=30)
    monto = models.IntegerField(blank=True, null=True)
    fecha = models.DateField(blank=True, null=True)
    kilos = models.FloatField(blank=True, null=True)
    usuario = models.CharField(max_length=30)
    especie = models.CharField(max_length=30)
    variedad = models.CharField(max_length=30)
    id_venta_local = models.ForeignKey('VentaLocal', models.DO_NOTHING, db_column='id_venta_local')

    class Meta:
        managed = False
        db_table = 'pago'


class Pais(models.Model):
    id_pais = models.IntegerField(primary_key=True)
    descripcion = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'pais'


class Provincia(models.Model):
    id_provincia = models.IntegerField(primary_key=True)
    des_provincia = models.CharField(max_length=50)
    id_region = models.ForeignKey('Region', models.DO_NOTHING, db_column='id_region')

    class Meta:
        managed = False
        db_table = 'provincia'


class Puntos(models.Model):
    id_puntos = models.IntegerField(primary_key=True)
    des_puntos = models.CharField(max_length=50)
    id_usuario = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usuario', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'puntos'


class Region(models.Model):
    id_region = models.IntegerField(primary_key=True)
    des_region = models.CharField(max_length=50)
    region_id = models.IntegerField(unique=True)

    class Meta:
        managed = False
        db_table = 'region'


class Rol(models.Model):
    id_rol = models.IntegerField(primary_key=True)
    des_rol = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'rol'


class Solicitud(models.Model):
    id_solicitud = models.IntegerField(primary_key=True)
    fecha_entrega = models.DateField(blank=True, null=True)
    fecha_creacion = models.DateField()
    fecha_de_termino = models.DateField(blank=True, null=True)
    id_usuario = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usuario')
    id_estado = models.ForeignKey(EstadoSolicitud, models.DO_NOTHING, db_column='id_estado', blank=True, null=True)
    

    class Meta:
        managed = False
        db_table = 'solicitud'


class StockSobrante(models.Model):
    id_stock = models.IntegerField(primary_key=True)
    kilo = models.IntegerField(blank=True, null=True)
    fecha_cosecha = models.DateField(blank=True, null=True)
    fecha_entrada = models.DateField(blank=True, null=True)
    id_orden = models.ForeignKey(OrdenCompra, models.DO_NOTHING, db_column='id_orden', blank=True, null=True)

feriaVirtual/core/templates/include/contactanos.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link href="https://fonts.googleapis.com/css?family=Barlow:400,700|Poppins:300,400&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/build/tailwind.css">
  <title>Tailwind - Movie Production Landing Page</title>
</head>
<body class="antialiased ">
  <header class="header relative lg:overflow-hidden"> 

    <div class="container mx-auto lg:mt-56 lg:px-16 px-4 py-4">
	<div>
        <h1 class="text-black md:text-4xl text-2xl font-bold font-sans m-0 md:leading-none">Trabaja con nosotros</h1>
        <p class="text-black text-lg  w-full md:my-4">Si eres productor o dueño de una empresa y quieres formar parte de esta compañía, por favor llena tus datos y envía tu petición para que uno de nuestros funcionarios se contacte a la brevedad con usted.</p>
      </div>
    </div>
  </header>


  
  <footer class="container mx-auto text-white py-6 md:px-16 px-4">

				<div style="width: 600px;">
				  <form action ="" method="POST">
					{% csrf_token %}
					<div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 flex flex-col">
					  <div class="-mx-3 md:flex mb-6">
						<div class="md:w-1/2 px-3 mb-6 md:mb-0">
						  <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="nombre" >
							Nombre*
						  </label>
						  
						  <input class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" id="nombre"  type="text" placeholder="Nombre *" name="nombre" required>
						  
						</div>
						<div class="md:w-1/2 px-3">
						  <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="subject">
							Asunto*
						  </label>
						  <input class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" id="subject" type="text" placeholder="Asunto" name="subject" required>
						
						</div>
						
						
					  </div>
					  <div class="-mx-3 md:flex mb-6">
						<div class="md:w-full px-3">
						  <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="email">
							Correo Electronico*
						  </label>

						  <input class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" type="email" id="email" name="email" placeholder="E-mail *" required>
						</div>
					  </div>
					  <div class="-mx-3 md:flex mb-3">
						<div class="md:w-1/2 px-3">
						  <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="fono">
							Fono*
						  </label>
						  <input class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" type="text" id="fono" name="fono" placeholder="Fono *" required>

						</div>
					  </div>
					  <div class="-mx-3 md:flex mb-2">
						<div class="md:w-full px-3 mb-6 md:mb-0">
						  <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="mensaje" >
							Mensaje*
						  </label>
						  <div>
							
							<textarea class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" id="mensaje" name="mensaje" placeholder="Mensaje *"  rows="5" required></textarea>
						  </div>
						</div>
						
					  </div>
					  <div class="-mx-3 md:flex mt-2">
						<div class="md:w-full px-3">
						  <button type="submit" class="md:w-full bg-gray-900 text-white font-bold py-2 px-4 border-b-4 hover:border-b-2 border-gray-500 hover:border-gray-100 rounded-full">
							Enviar
						  </button>
						</div>
					  </div>
					</div>
				  </form>
				</div>
  </footer>


</body>
</html>

feriaVirtual/core/templates/include/correo.html
<html>
    <head></head>
    <body>
        <h1> Se ha recibido una nueva solicitud de {{ Nombre }} </h1>
        <h4>Datos de contacto:</h4>
        <table>
    		<tr>
				<br>
                <td>Nombre: </td>
                <td> <u>{{Nombre}} </u> </td>
            </tr>
            <tr>
				<br>
                <td>correo: </td>
                <td> <u>{{Email}} </u> </td>
            </tr>
            <tr>
				<br>
                <td>Telefono: </td>
                <td> <u>{{fono}} </u> </td>
            </tr>
            
        </table>
        <h4>Mensaje:</h4>
        <p>
            {{mensaje}}
        </p>
    </body>
</html>

feriaVirtual/core/templates/include/dashboard-Resumen.html
{% load static %}
{%load humanize%}
{% block head %}
    <script src="{% static 'lib/highcharts-8.1.2/highcharts.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/exporting.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/export-data.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/accessibility.js' %}"></script>
    <link rel="stylesheet" href="{% static '../static/css/resumenAnio.css' %}"/>
{% endblock %}

    <div id="container"></div>

<script type="application/javascript">
Highcharts.chart('container', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Resumen del año 2020'
    },
    subtitle: {
        text: 'Exportaciones VS Venta Local'
    },
    xAxis: {
        categories: [
            'Enero',
            'Febrero',
            'Marzo',
            'Abril',
            'Mayo',
            'Junio',
            'Julio',
            'Agosto',
            'Septiembre',
            'Octubre',
            'Noviembre',
            'Diciembre'
            
        ],
        crosshair: true
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Valores $'
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.0f} $</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        }
    },
    series: [{
        name: 'Exportaciones',
        data: {{resumen_oc|safe}}

    }, {
        name: 'Venta Local',
        data: {{resumen_vl|safe}}

    }
    
    ]
});
</script>

feriaVirtual/core/templates/include/navbar.html
    <div class="contenedor-navbar grid grid-cols-1 md:grid-col-6">
        <div class="contenedor-menu flex justify-end border-b pr-4 md:hidden">
            <span class="py-4"><i class="fas fa-bars text-white text-3xl"></i></span>
        </div>
        <a href="/">
            <div class="contenedor-logo hidden md:flex centrar-contenedor"></div>
        </a>
    
        <div class="contenedor-enlace md:col-span-3">
            <ul class="contenedor-enlace__ul grid grid-cols-1 md:grid-cols-5">
            {% if perms.core.view_pago %}

                <a href="{% url 'home' %}"
                    class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0 ">
                    <li>Inicio</li>
                </a>
                <a href="#"
                    class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0 ">
                    <li></li>
                </a>
                <a href="#"
                    class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0 " id="send">
                    <li>Historial Compras</li>
                </a>
                <form action="{% url 'historial_compra' %}" method="POST" hidden="hidden">
                    {% csrf_token %}
                    <input type="hidden" value="{{user.username}}" name="valcorreo">
                    <input type="submit" id="subir_btn" name="subir_btn" value="historial_compra"  hidden="hidden"/>
                </form>
                <script>
                        const subir_btn = document.getElementById('subir_btn');
                        const send = document.getElementById('send');

                        send.addEventListener("click",function () {
    	                subir_btn.click();
                        });
                </script>
                <a href="javascript:enviar_formulario11()"
                    class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0 ">
                    <li>Cuenta</li>
                </a>
                <form action="{% url 'informacion' %}" method="GET" hidden="hidden" name="formulario11" >
                    {% csrf_token %}
                    <input type="hidden" value="{{request.user.username}}" name="valcorreo">
                </form>
                <script>
                    function enviar_formulario11(){
                    document.formulario11.submit()
                    }
                </script>
                
                <a href="#"
                    class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0 ">
                    <li>Puntos</li>
                </a>

            {% else %}
                {% if perms.core.view_solicitud %}
                                 
                    <a href="{% url 'home' %}"
                        class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0 ">
                        <li>Inicio</li>
                    </a>
                    <a href="#" class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0">
                        <li></li>
                    </a>
                    <a href="{% url 'solicitud' %}" class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0">
                        <li>Generar Solicitud</li>
                    </a>
                    <a href="javascript:enviar_formulario6()" class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0">
                        <li>Pedidos</li>
                    </a>
                    <form action="{% url 'pedido' %}" method="POST" hidden="hidden" name="formulario6">
                        {% csrf_token %}
                        <input type="hidden" value="{{user.username}}" name="valcorreo">
                    </form>
                        <script>
                            function enviar_formulario6(){
                            document.formulario6.submit()
                            }
                    </script>

                    <a href="javascript:enviar_formulario10()" class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0">
                        <li>Ordenes de Compra</li>
                    </a>    
                    <form action="{% url 'ordenesExterno' %}" method="POST" hidden="hidden" name="formulario10">
                        {% csrf_token %}
                        <input type="hidden" value="{{user.username}}" name="valcorreo">
                    </form>
                        <script>
                            function enviar_formulario10(){
                            document.formulario10.submit()
                            }
                    </script>
                {% else %}
                    {% if perms.core.view_detalleoferta %}
                    
                        <a href="{% url 'home' %}"
                            class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0 ">
                            <li>Inicio</li>
                        </a>
                        <a href="#" class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0">
                            <li></li>
                        </a>
                        <a href="javascript:enviar_formulario()" class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0">
                            <li>Historial de Ofertas</li>
                        </a>
                        <form action="{% url 'historial_ofertas' %}" method="POST" hidden="hidden" name="formulario3">
                            {% csrf_token %}
                            <input type="hidden" value="{{user.username}}" name="valcorreo">
                        </form>
                        <script>
                                function enviar_formulario(){
                                document.formulario3.submit()
                            }
                        </script>
                        <a href="{% url 'portalDeOfertas' %}" class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0">
                            <li>Portal de Ofertas</li>
                        </a>
                        <a href="#" class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0">
                            <li></li>
                        </a>
                    
                    {% else %}
                        {% if perms.core.view_ventalocal %}
                          
                           
                        {% else %}
                            <a href="{% url 'home' %}"

                                class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0 ">
                                <li>Inicio</li>
                            </a>
                            <a href="{% url 'info_empresa' %}" class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0">
                                <li>Empresa</li>
                            </a>
                            <a href="{% url 'contactanos' %}" class="contenedor-enlace__li centrar-contenedor py-4 hover:bg-green-600 md:p-0">
                                <li>Contactanos</li>
                            </a>
                            
                            
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
            </ul>
        </div>
        {% if user.is_authenticated %}
            <div class="contenedor-btn grid grid-cols-1 col-span-3 md:grid-col-2 md:col-span-2">
                <div class="centrar-contenedor py-2 md:py-0">
                    <a href="{% url 'logout' %}" class="btn btn-blue w-full md:w-48 hover:bg-blue-600"><span
                    class="text-white">Cerrar sesión</span></a>
                </div>
                <div class="centrar-contenedor py-2 md:py-0">
                    <a href="{% url 'usuario' %}" class="btn btn-orange w-full md:w-48 hover:bg-orange-600"><span
                    class="text-white"> {{user.get_full_name | upper}}</span></a>
                </div>
            </div>
        {% else %}
        <div class="contenedor-btn grid grid-cols-1 col-span-3 md:grid-col-2 md:col-span-2">
            <div class="centrar-contenedor py-2 md:py-0">
                <a href="{% url 'login' %}" class="btn btn-blue w-full md:w-48 hover:bg-blue-600"><span
                        class="text-white">Ingresar</span></a>
            </div>
            <div class="centrar-contenedor py-2 md:py-0">
                <a href="{% url 'registro' %}" class="btn btn-orange w-full md:w-48 hover:bg-orange-600"><span
                class="text-white">Registrarse</span></a>
            </div>
        </div>
        {% endif %}
    </div>